# We have 2 stage Test and Deploy
stages:
  - test
  - deploy

# Config cache
cache:
  paths:
    - node_modules/

# Test job
test:
  # Docker image
  image: node:latest
  # MySQL Services
  services:
    - mysql:latest
  # MySQL Variable
  variables:
    # Configure mysql service (https://hub.docker.com/_/mysql/)
    MYSQL_DATABASE: $MYSQL_DB
    MYSQL_ROOT_PASSWORD: $MYSQL_PASS
  # Attach Test job to Test stage
  stage: test
  # Config to use GitLab Shared Runner with Executor Docker
  tags:
    - docker
  script:
    - npm install
    - npm install -g sequelize-cli
    - sequelize db:migrate --env=test
    - npm run test
  # Defines the names of branches and tags the job runs for
  only:
    - mysql-ci-cd

# Deploy job
deploy:
  type: deploy
  # Attach Deploy job to Deploy stage
  stage: deploy
  # Config to use our Runner with Executor Shell
  tags:
    - hello
  script:
    # Only copy changed files to project folder
    - cp -r -u * .env* $PROJECT_DIR_MYSQL
    - cd $PROJECT_DIR_MYSQL
    - npm install
    - sequelize db:create --env=production
    - sequelize db:migrate --env=production
    # Restart NodeJS service
    - npm run stop || true
    - npm run start
  only:
    - mysql-ci-cd
